DROP TABLE IF EXISTS messages;

DROP TYPE IF EXISTS readstatus;
CREATE TYPE readstatus as ENUM(
    'seen',
    'not seen',
    'deleted'
);

CREATE TABLE messages (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    conversations_id INTEGER
        REFERENCES conversations(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER
        REFERENCES users(id),
    text TEXT,
    timestamp DATE DEFAULT now() NOT NULL,
    message_status readstatus

);